import {
  Activity, Airplay, AlarmClock, Archive, ArrowDownCircle, ArrowUpCircle,
  Award, Baby, Backpack, Banknote, Bell, Bike, Binoculars, Book, BookOpen,
  Bookmark, Bot, Box, Briefcase, Brush, Bug, Building, Bus, Cake, Calculator,
  Calendar, CalendarCheck, CalendarDays, Camera, Car, Cat,
  ChartBar, ChartLine, ChartPie, CheckCircle, ChefHat, Cherry, Circle,
  Clipboard, Clock, Cloud, CloudSun, Clover, Code, Coffee, Cog, Coins,
  Compass, Cookie, CreditCard, Crown, CupSoda, Database, Diamond, Disc,
  Dna, DollarSign, Download, DownloadCloud, DraftingCompass, Drum,
  Dumbbell, Ear, Earth, Edit, Egg, Ellipsis, Eraser, Euro, ExternalLink,
  Eye, Factory, Fan, Feather, File, FileImage, FileText, Film, Filter,
  Fingerprint, Fish, Flag, Flame, FlaskConical, Flower, Flower2, Folder,
  Footprints, ForkKnife, Frame, Frown, Fuel, Gamepad2, Gauge, Gem, Ghost,
  Gift, GitBranch, GitFork, GitMerge, GitPullRequest, GlassWater, Globe,
  Globe2, GraduationCap, Grape, Grip, Guitar, Ham, Hand, HandHelping,
  HandMetal, Handshake, HardDrive, HardHat, Hash, Haze, Headphones, Heart,
  HeartHandshake, Heater, HelpCircle, Hexagon, Highlighter, History, Home,
  Hop, Hourglass, IceCream, Image, Infinity, Info, Inspect, Joystick,
  Kanban, Key, Keyboard, Landmark, Languages, Laptop, Lasso, Layers,
  LayoutDashboard, LayoutGrid, LayoutList, Leaf, Library, Lightbulb, Link,
  List, ListMusic, Loader, Lock, LogIn, LogOut, Luggage, Magnet, Mail,
  Map, MapPin, MapPinned, Martini, Maximize2, Medal, Megaphone,
  Menu, MessageCircle, MessageSquare, MessagesSquare, Mic, Microscope,
  Microwave, Milestone, Milk, Minimize2, Minus, MinusCircle, Monitor,
  Moon, MoonStar, MoreHorizontal, MoreVertical, Mountain, MountainSnow,
  Mouse, MousePointer, Move3D, Music, Music2, Music3, Music4, Navigation,
  Navigation2, Network, Newspaper, Nfc, Nut, Octagon, Orbit, Package,
  Paintbrush, PaintBucket, Palette, Palmtree, Paperclip, ParkingCircle,
  PartyPopper, Pause, PawPrint, Pen, PenTool, Pencil, Pentagon, Percent,
  PersonStanding, Phone, Pi, PictureInPicture, PiggyBank, Pilcrow, Pin,
  Pipette, Pizza, Plane, Play, PlayCircle, PlugZap, Podcast,
  Pointer, Power, PowerCircle, Presentation, Printer, Projector, Puzzle,
  QrCode, Quote, Radar, Radio, Droplet, Rainbow, Receipt, Recycle, Redo,
  RefreshCcw, RefreshCw, Repeat, Repeat1, Reply, Rewind, Ribbon, Rocket,
  RockingChair, RollerCoaster, Rotate3D, RotateCcw, RotateCw, Route,
  Router, Ruler, Sailboat, Salad, Sandwich, Satellite, Save, Scale,
  Scan, Scissors, ScreenShare, Scroll, Search, Server, Settings, Share2,
  Shield, ShieldCheck, ShieldAlert, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, Shrub, Shuffle, Sigma, Signpost, Siren, SkipBack,
  SkipForward, Sliders, Smartphone, Smile, SmilePlus, Snowflake,
  Sofa, SortAsc, SortDesc, Sparkle, Sparkles, Speaker, Spline, SprayCan,
  Sprout, Square, SquarePen, Squirrel, Stamp, Star, StepBack, StepForward,
  Stethoscope, Sticker, StickyNote, StopCircle, Store, StretchHorizontal,
  StretchVertical, Subscript, Sun, SunDim, SunMedium, Sunrise, Sunset,
  Superscript, SwatchBook, SwitchCamera, Sword, Swords, Syringe, Table,
  Tablet, Tag, Tags, Target, Tent, Terminal, TestTube, Theater,
  Thermometer, ThumbsDown, ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight,
  Tornado, TowerControl, Train, Trash, Trash2, TreeDeciduous, TreePine,
  Trees, TrendingDown, TrendingUp, Triangle, Trophy, Truck, Turtle, Tv,
  Type, Umbrella, Underline, Undo, Ungroup, Unlink, Unlock, Upload,
  UploadCloud, Usb, User, UserCheck, UserCircle, UserCog, UserMinus,
  UserPlus, UserRound, UserRoundCheck, UserRoundPlus, UserRoundX,
  UserSearch, UserX, Users, UsersRound, Utensils, UtensilsCrossed,
  Variable, VenetianMask, Verified, Vibrate, Video, Videotape, View,
  Voicemail, Volume2, Vote, Wallet, WalletCards, Wallpaper, Wand, Wand2,
  Warehouse, Watch, Waves, Waypoints, Webcam, Webhook, Weight, Wheat,
  WholeWord, Wifi, Wind, Wine, Wrench, X, XCircle, Zap, ZapOff,
  ZoomIn, ZoomOut,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const iconRegistry: Record<string, LucideIcon> = {
  Activity, Airplay, AlarmClock, Archive, ArrowDownCircle, ArrowUpCircle,
  Award, Baby, Backpack, Banknote, Bell, Bike, Binoculars, Book, BookOpen,
  Bookmark, Bot, Box, Briefcase, Brush, Bug, Building, Bus, Cake, Calculator,
  Calendar, CalendarCheck, CalendarDays, Camera, Car, Cat,
  ChartBar, ChartLine, ChartPie, CheckCircle, ChefHat, Cherry, Circle,
  Clipboard, Clock, Cloud, CloudSun, Clover, Code, Coffee, Cog, Coins,
  Compass, Cookie, CreditCard, Crown, CupSoda, Database, Diamond, Disc,
  Dna, DollarSign, Download, DownloadCloud, DraftingCompass, Drum,
  Dumbbell, Ear, Earth, Edit, Egg, Ellipsis, Eraser, Euro, ExternalLink,
  Eye, Factory, Fan, Feather, File, FileImage, FileText, Film, Filter,
  Fingerprint, Fish, Flag, Flame, FlaskConical, Flower, Flower2, Folder,
  Footprints, ForkKnife, Frame, Frown, Fuel, Gamepad2, Gauge, Gem, Ghost,
  Gift, GitBranch, GitFork, GitMerge, GitPullRequest, GlassWater, Globe,
  Globe2, GraduationCap, Grape, Grip, Guitar, Ham, Hand, HandHelping,
  HandMetal, Handshake, HardDrive, HardHat, Hash, Haze, Headphones, Heart,
  HeartHandshake, Heater, HelpCircle, Hexagon, Highlighter, History, Home,
  Hop, Hourglass, IceCream, Image, Infinity, Info, Inspect, Joystick,
  Kanban, Key, Keyboard, Landmark, Languages, Laptop, Lasso, Layers,
  LayoutDashboard, LayoutGrid, LayoutList, Leaf, Library, Lightbulb, Link,
  List, ListMusic, Loader, Lock, LogIn, LogOut, Luggage, Magnet, Mail,
  Map, MapPin, MapPinned, Martini, Maximize2, Medal, Megaphone,
  Menu, MessageCircle, MessageSquare, MessagesSquare, Mic, Microscope,
  Microwave, Milestone, Milk, Minimize2, Minus, MinusCircle, Monitor,
  Moon, MoonStar, MoreHorizontal, MoreVertical, Mountain, MountainSnow,
  Mouse, MousePointer, Move3D, Music, Music2, Music3, Music4, Navigation,
  Navigation2, Network, Newspaper, Nfc, Nut, Octagon, Orbit, Package,
  Paintbrush, PaintBucket, Palette, Palmtree, Paperclip, ParkingCircle,
  PartyPopper, Pause, PawPrint, Pen, PenTool, Pencil, Pentagon, Percent,
  PersonStanding, Phone, Pi, PictureInPicture, PiggyBank, Pilcrow, Pin,
  Pipette, Pizza, Plane, Play, PlayCircle, PlugZap, Podcast,
  Pointer, Power, PowerCircle, Presentation, Printer, Projector, Puzzle,
  QrCode, Quote, Radar, Radio, Droplet, Rainbow, Receipt, Recycle, Redo,
  RefreshCcw, RefreshCw, Repeat, Repeat1, Reply, Rewind, Ribbon, Rocket,
  RockingChair, RollerCoaster, Rotate3D, RotateCcw, RotateCw, Route,
  Router, Ruler, Sailboat, Salad, Sandwich, Satellite, Save, Scale,
  Scan, Scissors, ScreenShare, Scroll, Search, Server, Settings, Share2,
  Shield, ShieldCheck, ShieldAlert, Ship, Shirt, ShoppingBag, ShoppingBasket,
  ShoppingCart, Shovel, Shrub, Shuffle, Sigma, Signpost, Siren, SkipBack,
  SkipForward, Sliders, Smartphone, Smile, SmilePlus, Snowflake,
  Sofa, SortAsc, SortDesc, Sparkle, Sparkles, Speaker, Spline, SprayCan,
  Sprout, Square, SquarePen, Squirrel, Stamp, Star, StepBack, StepForward,
  Stethoscope, Sticker, StickyNote, StopCircle, Store, StretchHorizontal,
  StretchVertical, Subscript, Sun, SunDim, SunMedium, Sunrise, Sunset,
  Superscript, SwatchBook, SwitchCamera, Sword, Swords, Syringe, Table,
  Tablet, Tag, Tags, Target, Tent, Terminal, TestTube, Theater,
  Thermometer, ThumbsDown, ThumbsUp, Ticket, Timer, ToggleLeft, ToggleRight,
  Tornado, TowerControl, Train, Trash, Trash2, TreeDeciduous, TreePine,
  Trees, TrendingDown, TrendingUp, Triangle, Trophy, Truck, Turtle, Tv,
  Type, Umbrella, Underline, Undo, Ungroup, Unlink, Unlock, Upload,
  UploadCloud, Usb, User, UserCheck, UserCircle, UserCog, UserMinus,
  UserPlus, UserRound, UserRoundCheck, UserRoundPlus, UserRoundX,
  UserSearch, UserX, Users, UsersRound, Utensils, UtensilsCrossed,
  Variable, VenetianMask, Verified, Vibrate, Video, Videotape, View,
  Voicemail, Volume2, Vote, Wallet, WalletCards, Wallpaper, Wand, Wand2,
  Warehouse, Watch, Waves, Waypoints, Webcam, Webhook, Weight, Wheat,
  WholeWord, Wifi, Wind, Wine, Wrench, X, XCircle, Zap, ZapOff,
  ZoomIn, ZoomOut,
}

export const PICKER_ICONS = Array.from(new Set([
  'Award', 'Trophy', 'Medal', 'Crown', 'Gem', 'Diamond', 'Star', 'Heart',
  'Shield', 'ShieldCheck', 'ShieldAlert', 'Flame', 'Snowflake', 'Music',
  'Music2', 'Music3', 'Music4', 'Zap', 'ZapOff', 'Rocket', 'Upload',
  'UploadCloud', 'Download', 'DownloadCloud', 'ArrowUpCircle', 'ArrowDownCircle',
  'HardDrive', 'Database', 'Package', 'Archive', 'Folder', 'File', 'FileImage',
  'FileText', 'Film', 'Camera', 'Image', 'Tv', 'Monitor', 'Tablet', 'Smartphone',
  'Laptop', 'Headphones', 'Speaker', 'Bell', 'Megaphone', 'MessageCircle',
  'MessageSquare', 'MessagesSquare', 'Mail', 'AtSign', 'ThumbsUp', 'ThumbsDown',
  'HeartHandshake', 'Handshake', 'HandHelping', 'User', 'Users', 'UsersRound',
  'UserPlus', 'UserCheck', 'UserMinus', 'UserX', 'UserCircle', 'UserCog',
  'UserRound', 'UserRoundPlus', 'UserRoundCheck', 'UserRoundX', 'Smile',
  'SmilePlus', 'Frown', 'Meh', 'Clock', 'Timer', 'AlarmClock', 'Hourglass',
  'Calendar', 'CalendarCheck', 'CalendarDays', 'History', 'Sun', 'SunDim',
  'SunMedium', 'Moon', 'MoonStar', 'Cloud', 'CloudSun', 'Droplet', 'Rainbow',
  'Droplet', 'CloudDrizzle', 'CloudLightning', 'Wind', 'Tornado', 'Leaf',
  'Flower', 'Flower2', 'TreeDeciduous', 'TreePine', 'Mountain', 'MountainSnow',
  'Palette', 'Paintbrush', 'PaintBucket', 'Pen', 'PenTool', 'Pencil',
  'Eraser', 'Highlighter', 'Brush', 'Edit', 'Wand', 'Wand2', 'Sparkle',
  'Sparkles', 'Lightbulb', 'Search', 'Eye', 'Lock', 'Unlock', 'Key', 'Cog',
  'Settings', 'Sliders', 'Filter', 'Tool', 'Wrench', 'Home', 'Map', 'MapPin',
  'MapPinned', 'Globe', 'Globe2', 'Compass', 'Navigation', 'Navigation2',
  'Flag', 'Target', 'Crosshair', 'Gift', 'ShoppingBag', 'ShoppingBasket',
  'ShoppingCart', 'CreditCard', 'Wallet', 'WalletCards', 'DollarSign',
  'Euro', 'Pound', 'Coins', 'Banknote', 'PiggyBank', 'Gamepad2', 'Joystick',
  'Dice', 'Dices', 'Puzzle', 'Book', 'BookOpen', 'Bookmark', 'Library',
  'Newspaper', 'Code', 'Terminal', 'GitBranch', 'GitFork', 'GitMerge',
  'GitPullRequest', 'Globe', 'Link', 'Share2', 'Cloud', 'Database',
  'Server', 'Box', 'Package', 'Anchor', 'Ship', 'Sailboat', 'Plane',
  'Car', 'Bike', 'Bus', 'Train', 'Truck', 'Rocket', 'Space',
  'Beaker', 'FlaskConical', 'Microscope', 'TestTube', 'Atom', 'Dna',
  'PawPrint', 'Cat', 'Dog', 'Fish', 'Rabbit', 'Snail', 'Turtle',
  'Bug', 'Bird', 'Bee', 'Butterfly', 'Crown', 'Feather', 'Cherry',
  'Apple', 'Grape', 'Lemon', 'Orange', 'Pizza', 'Cake', 'Coffee',
  'Beer', 'Wine', 'CupSoda', 'Martini', 'GlassWater', 'Utensils',
  'UtensilsCrossed', 'ForkKnife', 'ChefHat', 'Microwave', 'Refrigerator',
  'ToyBrick', 'Puzzle', 'Gamepad2', 'Dice5', 'Target', 'Sword',
  'Shield', 'Award', 'Trophy', 'Medal', 'Crown', 'Star',
]))

export function getIconByName(name: string): LucideIcon | undefined {
  return iconRegistry[name]
}

export const MEDAL_ICONS: Record<number, LucideIcon> = {
  4: Gem,
  8: Handshake,
  9: Palette,
  10: MoonStar,
  11: Trophy,
  12: Star,
  13: Shield,
  14: Medal,
  15: Flame,
  16: Heart,
  17: Crown,
  18: Snowflake,
  19: Music,
  20: Gem,
  21: Flower2,
  22: ShieldCheck,
}

export const MEDAL_COLORS: Record<number, string> = {
  4: '#FFD700',
  8: '#08979C',
  9: '#722ED1',
  10: '#1C1C3A',
  11: '#FFC107',
  12: '#FAAD14',
  13: '#BFBFBF',
  14: '#CD7F32',
  15: '#FF4D4F',
  16: '#FF4D4F',
  17: '#FFD700',
  18: '#69C0FF',
  19: '#EB2F96',
  20: '#36CFC9',
  21: '#FF85C0',
  22: '#1890FF',
}

export function getMedalIcon(code: number, dbIcon?: string): LucideIcon {
  if (dbIcon && iconRegistry[dbIcon]) return iconRegistry[dbIcon]
  return MEDAL_ICONS[code] ?? Medal
}

export function getMedalColor(code: number, dbColor?: string): string {
  return dbColor ?? MEDAL_COLORS[code] ?? '#8C8C8C'
}

export const ACHIEVEMENT_ICONS: Record<number, LucideIcon> = {
  0: Upload,
  1: UploadCloud,
  2: Timer,
  3: HeartHandshake,
  4: Award,
  5: CalendarCheck,
  6: MessageSquare,
  7: ArrowUpCircle,
  8: ArrowDownCircle,
  9: Clock,
  10: Rocket,
  11: ThumbsUp,
  12: MessageCircle,
  13: CalendarDays,
  14: UserPlus,
  15: Zap,
  16: HardDrive,
  17: AlarmClock,
  18: SquarePen,
  19: Heart,
  20: GitFork,
}

export const ACHIEVEMENT_COLORS: Record<number, string> = {
  0: '#1890FF',
  1: '#096DD9',
  2: '#52C41A',
  3: '#FF4D4F',
  4: '#FAAD14',
  5: '#722ED1',
  6: '#2F54EB',
  7: '#13C2C2',
  8: '#FA8C16',
  9: '#73D13D',
  10: '#FA541C',
  11: '#1890FF',
  12: '#531DAB',
  13: '#C41D7F',
  14: '#52C41A',
  15: '#FAAD14',
  16: '#13A8A8',
  17: '#F5222D',
  18: '#1D39C4',
  19: '#EB2F96',
  20: '#0050B3',
}

export function getAchievementIcon(code: number, dbIcon?: string): LucideIcon {
  if (dbIcon && iconRegistry[dbIcon]) return iconRegistry[dbIcon]
  return ACHIEVEMENT_ICONS[code] ?? Trophy
}

export function getAchievementColor(code: number, dbColor?: string): string {
  return dbColor ?? ACHIEVEMENT_COLORS[code] ?? '#8C8C8C'
}
