/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangUserRouteImport } from './routes/$lang/user_'
import { Route as LangTorrentsRouteImport } from './routes/$lang/torrents'
import { Route as LangRegisterRouteImport } from './routes/$lang/register'
import { Route as LangOffersRouteImport } from './routes/$lang/offers'
import { Route as LangMessagesRouteImport } from './routes/$lang/messages'
import { Route as LangMedalsRouteImport } from './routes/$lang/medals'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangInvitesRouteImport } from './routes/$lang/invites'
import { Route as LangHrRouteImport } from './routes/$lang/hr'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin.index'
import { Route as LangTorrentsUploadRouteImport } from './routes/$lang/torrents_.upload'
import { Route as LangTorrentsIdRouteImport } from './routes/$lang/torrents_.$id'
import { Route as LangAdminUsersRouteImport } from './routes/$lang/admin.users'
import { Route as LangAdminSettingsRouteImport } from './routes/$lang/admin.settings'
import { Route as LangAdminRolesRouteImport } from './routes/$lang/admin.roles'
import { Route as LangAdminReportsRouteImport } from './routes/$lang/admin.reports'
import { Route as LangAdminPromotionsRouteImport } from './routes/$lang/admin.promotions'
import { Route as LangAdminOperationsResourcesRouteImport } from './routes/$lang/admin.operations-resources'
import { Route as LangAdminMedalsRouteImport } from './routes/$lang/admin.medals'
import { Route as LangAdminLevelsRouteImport } from './routes/$lang/admin.levels'
import { Route as LangAdminDictRouteImport } from './routes/$lang/admin.dict'
import { Route as LangAdminClientRiskControlRouteImport } from './routes/$lang/admin.client-risk-control'
import { Route as LangAdminBonusRouteImport } from './routes/$lang/admin.bonus'
import { Route as LangAdminAnnouncementsRouteImport } from './routes/$lang/admin.announcements'
import { Route as LangTorrentsIdEditRouteImport } from './routes/$lang/torrents_.$id.edit'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangUserRoute = LangUserRouteImport.update({
  id: '/user_',
  path: '/user',
  getParentRoute: () => LangRoute,
} as any)
const LangTorrentsRoute = LangTorrentsRouteImport.update({
  id: '/torrents',
  path: '/torrents',
  getParentRoute: () => LangRoute,
} as any)
const LangRegisterRoute = LangRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LangRoute,
} as any)
const LangOffersRoute = LangOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LangRoute,
} as any)
const LangMessagesRoute = LangMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => LangRoute,
} as any)
const LangMedalsRoute = LangMedalsRouteImport.update({
  id: '/medals',
  path: '/medals',
  getParentRoute: () => LangRoute,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangRoute,
} as any)
const LangInvitesRoute = LangInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => LangRoute,
} as any)
const LangHrRoute = LangHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangTorrentsUploadRoute = LangTorrentsUploadRouteImport.update({
  id: '/torrents_/upload',
  path: '/torrents/upload',
  getParentRoute: () => LangRoute,
} as any)
const LangTorrentsIdRoute = LangTorrentsIdRouteImport.update({
  id: '/torrents_/$id',
  path: '/torrents/$id',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminUsersRoute = LangAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSettingsRoute = LangAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminRolesRoute = LangAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminReportsRoute = LangAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminPromotionsRoute = LangAdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminOperationsResourcesRoute =
  LangAdminOperationsResourcesRouteImport.update({
    id: '/operations-resources',
    path: '/operations-resources',
    getParentRoute: () => LangAdminRoute,
  } as any)
const LangAdminMedalsRoute = LangAdminMedalsRouteImport.update({
  id: '/medals',
  path: '/medals',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminLevelsRoute = LangAdminLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminDictRoute = LangAdminDictRouteImport.update({
  id: '/dict',
  path: '/dict',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminClientRiskControlRoute =
  LangAdminClientRiskControlRouteImport.update({
    id: '/client-risk-control',
    path: '/client-risk-control',
    getParentRoute: () => LangAdminRoute,
  } as any)
const LangAdminBonusRoute = LangAdminBonusRouteImport.update({
  id: '/bonus',
  path: '/bonus',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminAnnouncementsRoute = LangAdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangTorrentsIdEditRoute = LangTorrentsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LangTorrentsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/hr': typeof LangHrRoute
  '/$lang/invites': typeof LangInvitesRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/medals': typeof LangMedalsRoute
  '/$lang/messages': typeof LangMessagesRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/torrents': typeof LangTorrentsRoute
  '/$lang/user': typeof LangUserRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/announcements': typeof LangAdminAnnouncementsRoute
  '/$lang/admin/bonus': typeof LangAdminBonusRoute
  '/$lang/admin/client-risk-control': typeof LangAdminClientRiskControlRoute
  '/$lang/admin/dict': typeof LangAdminDictRoute
  '/$lang/admin/levels': typeof LangAdminLevelsRoute
  '/$lang/admin/medals': typeof LangAdminMedalsRoute
  '/$lang/admin/operations-resources': typeof LangAdminOperationsResourcesRoute
  '/$lang/admin/promotions': typeof LangAdminPromotionsRoute
  '/$lang/admin/reports': typeof LangAdminReportsRoute
  '/$lang/admin/roles': typeof LangAdminRolesRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/torrents/$id': typeof LangTorrentsIdRouteWithChildren
  '/$lang/torrents/upload': typeof LangTorrentsUploadRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/torrents/$id/edit': typeof LangTorrentsIdEditRoute
}
export interface FileRoutesByTo {
  '/$lang/hr': typeof LangHrRoute
  '/$lang/invites': typeof LangInvitesRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/medals': typeof LangMedalsRoute
  '/$lang/messages': typeof LangMessagesRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/torrents': typeof LangTorrentsRoute
  '/$lang/user': typeof LangUserRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin/announcements': typeof LangAdminAnnouncementsRoute
  '/$lang/admin/bonus': typeof LangAdminBonusRoute
  '/$lang/admin/client-risk-control': typeof LangAdminClientRiskControlRoute
  '/$lang/admin/dict': typeof LangAdminDictRoute
  '/$lang/admin/levels': typeof LangAdminLevelsRoute
  '/$lang/admin/medals': typeof LangAdminMedalsRoute
  '/$lang/admin/operations-resources': typeof LangAdminOperationsResourcesRoute
  '/$lang/admin/promotions': typeof LangAdminPromotionsRoute
  '/$lang/admin/reports': typeof LangAdminReportsRoute
  '/$lang/admin/roles': typeof LangAdminRolesRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/torrents/$id': typeof LangTorrentsIdRouteWithChildren
  '/$lang/torrents/upload': typeof LangTorrentsUploadRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/torrents/$id/edit': typeof LangTorrentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/hr': typeof LangHrRoute
  '/$lang/invites': typeof LangInvitesRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/medals': typeof LangMedalsRoute
  '/$lang/messages': typeof LangMessagesRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/register': typeof LangRegisterRoute
  '/$lang/torrents': typeof LangTorrentsRoute
  '/$lang/user_': typeof LangUserRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/announcements': typeof LangAdminAnnouncementsRoute
  '/$lang/admin/bonus': typeof LangAdminBonusRoute
  '/$lang/admin/client-risk-control': typeof LangAdminClientRiskControlRoute
  '/$lang/admin/dict': typeof LangAdminDictRoute
  '/$lang/admin/levels': typeof LangAdminLevelsRoute
  '/$lang/admin/medals': typeof LangAdminMedalsRoute
  '/$lang/admin/operations-resources': typeof LangAdminOperationsResourcesRoute
  '/$lang/admin/promotions': typeof LangAdminPromotionsRoute
  '/$lang/admin/reports': typeof LangAdminReportsRoute
  '/$lang/admin/roles': typeof LangAdminRolesRoute
  '/$lang/admin/settings': typeof LangAdminSettingsRoute
  '/$lang/admin/users': typeof LangAdminUsersRoute
  '/$lang/torrents_/$id': typeof LangTorrentsIdRouteWithChildren
  '/$lang/torrents_/upload': typeof LangTorrentsUploadRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/torrents_/$id/edit': typeof LangTorrentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/hr'
    | '/$lang/invites'
    | '/$lang/login'
    | '/$lang/medals'
    | '/$lang/messages'
    | '/$lang/offers'
    | '/$lang/register'
    | '/$lang/torrents'
    | '/$lang/user'
    | '/$lang/'
    | '/$lang/admin/announcements'
    | '/$lang/admin/bonus'
    | '/$lang/admin/client-risk-control'
    | '/$lang/admin/dict'
    | '/$lang/admin/levels'
    | '/$lang/admin/medals'
    | '/$lang/admin/operations-resources'
    | '/$lang/admin/promotions'
    | '/$lang/admin/reports'
    | '/$lang/admin/roles'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/torrents/$id'
    | '/$lang/torrents/upload'
    | '/$lang/admin/'
    | '/$lang/torrents/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$lang/hr'
    | '/$lang/invites'
    | '/$lang/login'
    | '/$lang/medals'
    | '/$lang/messages'
    | '/$lang/offers'
    | '/$lang/register'
    | '/$lang/torrents'
    | '/$lang/user'
    | '/$lang'
    | '/$lang/admin/announcements'
    | '/$lang/admin/bonus'
    | '/$lang/admin/client-risk-control'
    | '/$lang/admin/dict'
    | '/$lang/admin/levels'
    | '/$lang/admin/medals'
    | '/$lang/admin/operations-resources'
    | '/$lang/admin/promotions'
    | '/$lang/admin/reports'
    | '/$lang/admin/roles'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/torrents/$id'
    | '/$lang/torrents/upload'
    | '/$lang/admin'
    | '/$lang/torrents/$id/edit'
  id:
    | '__root__'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/hr'
    | '/$lang/invites'
    | '/$lang/login'
    | '/$lang/medals'
    | '/$lang/messages'
    | '/$lang/offers'
    | '/$lang/register'
    | '/$lang/torrents'
    | '/$lang/user_'
    | '/$lang/'
    | '/$lang/admin/announcements'
    | '/$lang/admin/bonus'
    | '/$lang/admin/client-risk-control'
    | '/$lang/admin/dict'
    | '/$lang/admin/levels'
    | '/$lang/admin/medals'
    | '/$lang/admin/operations-resources'
    | '/$lang/admin/promotions'
    | '/$lang/admin/reports'
    | '/$lang/admin/roles'
    | '/$lang/admin/settings'
    | '/$lang/admin/users'
    | '/$lang/torrents_/$id'
    | '/$lang/torrents_/upload'
    | '/$lang/admin/'
    | '/$lang/torrents_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/user_': {
      id: '/$lang/user_'
      path: '/user'
      fullPath: '/$lang/user'
      preLoaderRoute: typeof LangUserRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/torrents': {
      id: '/$lang/torrents'
      path: '/torrents'
      fullPath: '/$lang/torrents'
      preLoaderRoute: typeof LangTorrentsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/register': {
      id: '/$lang/register'
      path: '/register'
      fullPath: '/$lang/register'
      preLoaderRoute: typeof LangRegisterRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/offers': {
      id: '/$lang/offers'
      path: '/offers'
      fullPath: '/$lang/offers'
      preLoaderRoute: typeof LangOffersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/messages': {
      id: '/$lang/messages'
      path: '/messages'
      fullPath: '/$lang/messages'
      preLoaderRoute: typeof LangMessagesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/medals': {
      id: '/$lang/medals'
      path: '/medals'
      fullPath: '/$lang/medals'
      preLoaderRoute: typeof LangMedalsRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/invites': {
      id: '/$lang/invites'
      path: '/invites'
      fullPath: '/$lang/invites'
      preLoaderRoute: typeof LangInvitesRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/hr': {
      id: '/$lang/hr'
      path: '/hr'
      fullPath: '/$lang/hr'
      preLoaderRoute: typeof LangHrRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/torrents_/upload': {
      id: '/$lang/torrents_/upload'
      path: '/torrents/upload'
      fullPath: '/$lang/torrents/upload'
      preLoaderRoute: typeof LangTorrentsUploadRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/torrents_/$id': {
      id: '/$lang/torrents_/$id'
      path: '/torrents/$id'
      fullPath: '/$lang/torrents/$id'
      preLoaderRoute: typeof LangTorrentsIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/users': {
      id: '/$lang/admin/users'
      path: '/users'
      fullPath: '/$lang/admin/users'
      preLoaderRoute: typeof LangAdminUsersRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/settings': {
      id: '/$lang/admin/settings'
      path: '/settings'
      fullPath: '/$lang/admin/settings'
      preLoaderRoute: typeof LangAdminSettingsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/roles': {
      id: '/$lang/admin/roles'
      path: '/roles'
      fullPath: '/$lang/admin/roles'
      preLoaderRoute: typeof LangAdminRolesRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/reports': {
      id: '/$lang/admin/reports'
      path: '/reports'
      fullPath: '/$lang/admin/reports'
      preLoaderRoute: typeof LangAdminReportsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/promotions': {
      id: '/$lang/admin/promotions'
      path: '/promotions'
      fullPath: '/$lang/admin/promotions'
      preLoaderRoute: typeof LangAdminPromotionsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/operations-resources': {
      id: '/$lang/admin/operations-resources'
      path: '/operations-resources'
      fullPath: '/$lang/admin/operations-resources'
      preLoaderRoute: typeof LangAdminOperationsResourcesRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/medals': {
      id: '/$lang/admin/medals'
      path: '/medals'
      fullPath: '/$lang/admin/medals'
      preLoaderRoute: typeof LangAdminMedalsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/levels': {
      id: '/$lang/admin/levels'
      path: '/levels'
      fullPath: '/$lang/admin/levels'
      preLoaderRoute: typeof LangAdminLevelsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/dict': {
      id: '/$lang/admin/dict'
      path: '/dict'
      fullPath: '/$lang/admin/dict'
      preLoaderRoute: typeof LangAdminDictRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/client-risk-control': {
      id: '/$lang/admin/client-risk-control'
      path: '/client-risk-control'
      fullPath: '/$lang/admin/client-risk-control'
      preLoaderRoute: typeof LangAdminClientRiskControlRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/bonus': {
      id: '/$lang/admin/bonus'
      path: '/bonus'
      fullPath: '/$lang/admin/bonus'
      preLoaderRoute: typeof LangAdminBonusRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/announcements': {
      id: '/$lang/admin/announcements'
      path: '/announcements'
      fullPath: '/$lang/admin/announcements'
      preLoaderRoute: typeof LangAdminAnnouncementsRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/torrents_/$id/edit': {
      id: '/$lang/torrents_/$id/edit'
      path: '/edit'
      fullPath: '/$lang/torrents/$id/edit'
      preLoaderRoute: typeof LangTorrentsIdEditRouteImport
      parentRoute: typeof LangTorrentsIdRoute
    }
  }
}

interface LangAdminRouteChildren {
  LangAdminAnnouncementsRoute: typeof LangAdminAnnouncementsRoute
  LangAdminBonusRoute: typeof LangAdminBonusRoute
  LangAdminClientRiskControlRoute: typeof LangAdminClientRiskControlRoute
  LangAdminDictRoute: typeof LangAdminDictRoute
  LangAdminLevelsRoute: typeof LangAdminLevelsRoute
  LangAdminMedalsRoute: typeof LangAdminMedalsRoute
  LangAdminOperationsResourcesRoute: typeof LangAdminOperationsResourcesRoute
  LangAdminPromotionsRoute: typeof LangAdminPromotionsRoute
  LangAdminReportsRoute: typeof LangAdminReportsRoute
  LangAdminRolesRoute: typeof LangAdminRolesRoute
  LangAdminSettingsRoute: typeof LangAdminSettingsRoute
  LangAdminUsersRoute: typeof LangAdminUsersRoute
  LangAdminIndexRoute: typeof LangAdminIndexRoute
}

const LangAdminRouteChildren: LangAdminRouteChildren = {
  LangAdminAnnouncementsRoute: LangAdminAnnouncementsRoute,
  LangAdminBonusRoute: LangAdminBonusRoute,
  LangAdminClientRiskControlRoute: LangAdminClientRiskControlRoute,
  LangAdminDictRoute: LangAdminDictRoute,
  LangAdminLevelsRoute: LangAdminLevelsRoute,
  LangAdminMedalsRoute: LangAdminMedalsRoute,
  LangAdminOperationsResourcesRoute: LangAdminOperationsResourcesRoute,
  LangAdminPromotionsRoute: LangAdminPromotionsRoute,
  LangAdminReportsRoute: LangAdminReportsRoute,
  LangAdminRolesRoute: LangAdminRolesRoute,
  LangAdminSettingsRoute: LangAdminSettingsRoute,
  LangAdminUsersRoute: LangAdminUsersRoute,
  LangAdminIndexRoute: LangAdminIndexRoute,
}

const LangAdminRouteWithChildren = LangAdminRoute._addFileChildren(
  LangAdminRouteChildren,
)

interface LangTorrentsIdRouteChildren {
  LangTorrentsIdEditRoute: typeof LangTorrentsIdEditRoute
}

const LangTorrentsIdRouteChildren: LangTorrentsIdRouteChildren = {
  LangTorrentsIdEditRoute: LangTorrentsIdEditRoute,
}

const LangTorrentsIdRouteWithChildren = LangTorrentsIdRoute._addFileChildren(
  LangTorrentsIdRouteChildren,
)

interface LangRouteChildren {
  LangAdminRoute: typeof LangAdminRouteWithChildren
  LangHrRoute: typeof LangHrRoute
  LangInvitesRoute: typeof LangInvitesRoute
  LangLoginRoute: typeof LangLoginRoute
  LangMedalsRoute: typeof LangMedalsRoute
  LangMessagesRoute: typeof LangMessagesRoute
  LangOffersRoute: typeof LangOffersRoute
  LangRegisterRoute: typeof LangRegisterRoute
  LangTorrentsRoute: typeof LangTorrentsRoute
  LangUserRoute: typeof LangUserRoute
  LangIndexRoute: typeof LangIndexRoute
  LangTorrentsIdRoute: typeof LangTorrentsIdRouteWithChildren
  LangTorrentsUploadRoute: typeof LangTorrentsUploadRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAdminRoute: LangAdminRouteWithChildren,
  LangHrRoute: LangHrRoute,
  LangInvitesRoute: LangInvitesRoute,
  LangLoginRoute: LangLoginRoute,
  LangMedalsRoute: LangMedalsRoute,
  LangMessagesRoute: LangMessagesRoute,
  LangOffersRoute: LangOffersRoute,
  LangRegisterRoute: LangRegisterRoute,
  LangTorrentsRoute: LangTorrentsRoute,
  LangUserRoute: LangUserRoute,
  LangIndexRoute: LangIndexRoute,
  LangTorrentsIdRoute: LangTorrentsIdRouteWithChildren,
  LangTorrentsUploadRoute: LangTorrentsUploadRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
